### ISSUE TITLE
FIB race condition: Can add routes to RIB before FIB is ready

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#12]
I discovered that I can add rib routes quickly after 'goes start', and these routes will never make it to the fib.  I think it is because linux installs the routes immediately, but fib is not ready yet (maybe because it requires next-hop /32 but linux does not?).

I wrote a script that repros the fail:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ cat quick_add_routes.py
#!/bin/bash

set -x -e

goes stop
goes start

sleep 6

/sbin/ifdown eth-$1-0
/sbin/ifup eth-$1-0

/usr/bin/goes vnet set ha sp eth-$1-0 auto
/usr/bin/goes vnet set ha sp eth-$1-0 100g
/usr/bin/goes vnet set ha sp eth-$1-0 auto dis
/usr/bin/goes vnet set ha sp eth-$1-0 auto ena

sleep 1

#for i in {1..255};
for i in `seq 0 2 255`;
  do ip ro add 20.0.0.$i/31 via 192.168.155.2;
  #do echo "20.0.0.$i/31 via 192.168.155.2";
done
```

The next-hop is 192.168.155.2 which is a neighboring router on this invader's eth-31-0.

After 'goes start', eth-31-0 is in the following state:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh fe1 po m | ta
il
eth-24-0  false       false        false
eth-25-0  false       false        false
eth-26-0  false       false        false
eth-27-0  false       false        false
eth-28-0  false       false        false
eth-29-0  false       false        false
eth-30-0  false       false        false
eth-31-0  false        true        false
```

To get the link in "true true true", I do the autoneg "dance" at the top of the script.
```
/usr/bin/goes vnet set ha sp eth-$1-0 auto
/usr/bin/goes vnet set ha sp eth-$1-0 100g
/usr/bin/goes vnet set ha sp eth-$1-0 auto dis
/usr/bin/goes vnet set ha sp eth-$1-0 auto ena
```

Where $1 is "31" because I run the repro script like so:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ./quick_add_routes.py  31
```

The script installs ~128 static routes.  These routes are installed in rib:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ ip ro
default via 192.168.101.2 dev eth0
10.2.0.0/16 dev flannel.1  proto kernel  scope link  src 10.2.65.0
10.2.65.0/24 dev docker0  proto kernel  scope link  src 10.2.65.1
20.0.0.0/31 via 192.168.155.2 dev eth-31-0
20.0.0.2/31 via 192.168.155.2 dev eth-31-0
20.0.0.4/31 via 192.168.155.2 dev eth-31-0
20.0.0.6/31 via 192.168.155.2 dev eth-31-0
20.0.0.8/31 via 192.168.155.2 dev eth-31-0
20.0.0.10/31 via 192.168.155.2 dev eth-31-0
20.0.0.12/31 via 192.168.155.2 dev eth-31-0
20.0.0.14/31 via 192.168.155.2 dev eth-31-0
20.0.0.16/31 via 192.168.155.2 dev eth-31-0
20.0.0.18/31 via 192.168.155.2 dev eth-31-0
20.0.0.20/31 via 192.168.155.2 dev eth-31-0
<...>
20.0.0.242/31 via 192.168.155.2 dev eth-31-0
20.0.0.244/31 via 192.168.155.2 dev eth-31-0
20.0.0.246/31 via 192.168.155.2 dev eth-31-0
20.0.0.248/31 via 192.168.155.2 dev eth-31-0
20.0.0.250/31 via 192.168.155.2 dev eth-31-0
20.0.0.252/31 via 192.168.155.2 dev eth-31-0
20.0.0.254/31 via 192.168.155.2 dev eth-31-0
172.17.0.0/16 dev br-131bf7797fb8  proto kernel  scope link  src 172.17.0.1
172.19.0.0/16 dev br-e7353579d7a2  proto kernel  scope link  src 172.19.0.1
192.168.101.0/24 dev eth0  proto kernel  scope link  src 192.168.101.128
192.168.155.0/24 dev eth-31-0  proto kernel  scope link  src 192.168.155.3
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
```

BUT never make it to the fib.
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib
 Table                   Destination           Adjacency
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.3/32  2: local eth-31-0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
```

MOREOVER when i manually install a route:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ip ro add 30.0.0.240/31 via 192.168.155.2
```

The new route is not added to fib:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib
 Table                   Destination           Adjacency
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.3/32  2: local eth-31-0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
```

Then I add a 2nd 30.x.x.x route:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ip ro add 30.0.0.242/31 via 192.168.155.2
```

The 2nd 30.x.x.x route appears in fib:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib
 Table                   Destination           Adjacency
     0                   20.0.0.0/31  4: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0                 30.0.0.242/31  4: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.2/32  3: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0              192.168.155.3/32  2: local eth-31-0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
```

And now, we see `192.168.155.2/32` for the first time.

The 1st 30.x.x.x route is indeed in the rib:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ ip ro | grep "30.0.0.240"
30.0.0.240/31 via 192.168.155.2 dev eth-31-0
```

But not in the fib:
```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib | grep "30.0.0.240"
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib | grep "30.0.0.242"
     0                 30.0.0.242/31  4: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
```

It feels like "the pump needs to be primed" somewhere, before the routes are installed in the fib.

Maybe vnet requires NH 192.168.155.2/32 but linux does not.

**Comment by dlobete** [comment]
On Mon, Jan 23, 2017 at 1:58 PM, Donn Lee <notifications@github.com> wrote:

> I discovered that I can add rib routes quickly after 'goes start', and
> these routes will never make it to the fib. I think it is because linux
> installs the routes immediately, but fib is not ready yet (maybe because it
> requires next-hop /32 but linux does not?).
>
> I wrote a script that repros the fail:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ cat quick_add_routes.py
> #!/bin/bash
>
> set -x -e
>
> goes stop
> goes start
>
> sleep 6
>
> /sbin/ifdown eth-$1-0
> /sbin/ifup eth-$1-0
>
> /usr/bin/goes vnet set ha sp eth-$1-0 auto
> /usr/bin/goes vnet set ha sp eth-$1-0 100g
> /usr/bin/goes vnet set ha sp eth-$1-0 auto dis
> /usr/bin/goes vnet set ha sp eth-$1-0 auto ena
>
> sleep 1
>
> #for i in {1..255};
> for i in `seq 0 2 255`;
>   do ip ro add 20.0.0.$i/31 via 192.168.155.2;
>   #do echo "20.0.0.$i/31 via 192.168.155.2";
> done
>
> The next-hop is 192.168.155.2 which is a neighboring router on this
> invader's eth-31-0.
>
> After 'goes start', eth-31-0 is in the following state:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh fe1 po m | ta
> il
> eth-24-0  false       false        false
> eth-25-0  false       false        false
> eth-26-0  false       false        false
> eth-27-0  false       false        false
> eth-28-0  false       false        false
> eth-29-0  false       false        false
> eth-30-0  false       false        false
> eth-31-0  false        true        false
>
> To get the link in "true true true", I do the autoneg "dance" at the top
> of the script.
>
> /usr/bin/goes vnet set ha sp eth-$1-0 auto
> /usr/bin/goes vnet set ha sp eth-$1-0 100g
> /usr/bin/goes vnet set ha sp eth-$1-0 auto dis
> /usr/bin/goes vnet set ha sp eth-$1-0 auto ena
>
> Where $1 is "31" because I run the repro script like so:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ./quick_add_routes.py  31
>
> The script installs ~128 static routes. These routes are installed in rib:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ ip ro
> default via 192.168.101.2 dev eth010.2.0.0/16 dev flannel.1  proto kernel  scope link  src 10.2.65.010.2.65.0/24 dev docker0  proto kernel  scope link  src 10.2.65.120.0.0.0/31 via 192.168.155.2 dev eth-31-020.0.0.2/31 via 192.168.155.2 dev eth-31-020.0.0.4/31 via 192.168.155.2 dev eth-31-020.0.0.6/31 via 192.168.155.2 dev eth-31-020.0.0.8/31 via 192.168.155.2 dev eth-31-020.0.0.10/31 via 192.168.155.2 dev eth-31-020.0.0.12/31 via 192.168.155.2 dev eth-31-020.0.0.14/31 via 192.168.155.2 dev eth-31-020.0.0.16/31 via 192.168.155.2 dev eth-31-020.0.0.18/31 via 192.168.155.2 dev eth-31-020.0.0.20/31 via 192.168.155.2 dev eth-31-0
> <...>20.0.0.242/31 via 192.168.155.2 dev eth-31-020.0.0.244/31 via 192.168.155.2 dev eth-31-020.0.0.246/31 via 192.168.155.2 dev eth-31-020.0.0.248/31 via 192.168.155.2 dev eth-31-020.0.0.250/31 via 192.168.155.2 dev eth-31-020.0.0.252/31 via 192.168.155.2 dev eth-31-020.0.0.254/31 via 192.168.155.2 dev eth-31-0172.17.0.0/16 dev br-131bf7797fb8  proto kernel  scope link  src 172.17.0.1172.19.0.0/16 dev br-e7353579d7a2  proto kernel  scope link  src 172.19.0.1192.168.101.0/24 dev eth0  proto kernel  scope link  src 192.168.101.128192.168.155.0/24 dev eth-31-0  proto kernel  scope link  src 192.168.155.3
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> BUT never make it to the fib.
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib
>  Table                   Destination           Adjacency
>      0              192.168.155.0/24  1: glean eth-31-0
>      0              192.168.155.3/32  2: local eth-31-0
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> MOREOVER when i manually install a route:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ip ro add 30.0.0.240/31 via 192.168.155.2
>
> The new route is not added to fib:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib
>  Table                   Destination           Adjacency
>      0              192.168.155.0/24  1: glean eth-31-0
>      0              192.168.155.3/32  2: local eth-31-0
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> Then I add a 2nd 30.x.x.x route:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ip ro add 30.0.0.242/31 via 192.168.155.2
>
> The 2nd 30.x.x.x route appears in fib:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib
>  Table                   Destination           Adjacency
>      0                   20.0.0.0/31  4: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
>      0                 30.0.0.242/31  4: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
>      0              192.168.155.0/24  1: glean eth-31-0
>      0              192.168.155.2/32  3: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
>      0              192.168.155.3/32  2: local eth-31-0
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> And now, we see 192.168.155.2/32 for the first time.
>
> The 1st 30.x.x.x route is indeed in the rib:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ ip ro | grep "30.0.0.240"30.0.0.240/31 via 192.168.155.2 dev eth-31-0
>
> But not in the fib:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib | grep "30.0.0.240"
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh ip fib | grep "30.0.0.242"
>      0                 30.0.0.242/31  4: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> It feels like "the pump needs to be primed" somewhere, before the routes
> are installed in the fib.
>
> Maybe vnet requires NH 192.168.155.2/32 but linux does not.
>

Exactly what I was about to say Donn. It's a known vnet behavior that it
doesn't install a route that has no adjacency. When is the adjacency added
in the script ?

Don.

**Comment by tgrennan** [comment]
It doesn't matter much but "quick_add_routes.py" is a bash, not python
script.

Also, I think you should add something like these DEV entries to
/etc/network/interfaces or separate /etc/network/interfaces.d/DEV files
with something like:

allow-vnet eth-PORT-SUBPORT
iface eth-PORT-SUBPORT inet static
  address #.#.#.#
  netmask #.#.#.#
  dns-nameservers #.#.#.# ...

And use something like this for '/etc/network/if-up.d/static-routes':

#!/bin/bash

case "$IFACE" in
eth-PORT-SUBPORT)
    for i in `seq 0 2 255`; do
        ip ro add 20.0.0.$i/31 via 192.168.155.2 [dev $IFACE]
    done
    ;;
esac

And a similar script to remove such routes in
'etc/network/if-down.d/static-routes'

goes start/stop will then execute the above.


On Mon, Jan 23, 2017 at 1:58 PM Donn Lee <notifications@github.com> wrote:

I discovered that I can add rib routes quickly after 'goes start', and
these routes will never make it to the fib. I think it is because linux
installs the routes immediately, but fib is not ready yet (maybe because it
requires next-hop /32 but linux does not?).

I wrote a script that repros the fail:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
cat quick_add_routes.py
#!/bin/bash

set -x -e

goes stop
goes start

sleep 6

/sbin/ifdown eth-$1-0
/sbin/ifup eth-$1-0

/usr/bin/goes vnet set ha sp eth-$1-0 auto
/usr/bin/goes vnet set ha sp eth-$1-0 100g
/usr/bin/goes vnet set ha sp eth-$1-0 auto dis
/usr/bin/goes vnet set ha sp eth-$1-0 auto ena

sleep 1

#for i in {1..255};
for i in `seq 0 2 255`;
  do ip ro add 20.0.0.$i/31 via 192.168.155.2;
  #do echo "20.0.0.$i/31 via 192.168.155.2";
done

The next-hop is 192.168.155.2 which is a neighboring router on this
invader's eth-31-0.

After 'goes start', eth-31-0 is in the following state:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh fe1 po m | ta
il
eth-24-0  false       false        false
eth-25-0  false       false        false
eth-26-0  false       false        false
eth-27-0  false       false        false
eth-28-0  false       false        false
eth-29-0  false       false        false
eth-30-0  false       false        false
eth-31-0  false        true        false

To get the link in "true true true", I do the autoneg "dance" at the top of
the script.

/usr/bin/goes vnet set ha sp eth-$1-0 auto
/usr/bin/goes vnet set ha sp eth-$1-0 100g
/usr/bin/goes vnet set ha sp eth-$1-0 auto dis
/usr/bin/goes vnet set ha sp eth-$1-0 auto ena

Where $1 is "31" because I run the repro script like so:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
sudo ./quick_add_routes.py  31

The script installs ~128 static routes. These routes are installed in rib:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
ip ro
default via 192.168.101.2 dev eth010.2.0.0/16 dev flannel.1  proto
kernel  scope link  src 10.2.65.010.2.65.0/24 dev docker0  proto
kernel  scope link  src 10.2.65.120.0.0.0/31 via 192.168.155.2 dev
eth-31-020.0.0.2/31 via 192.168.155.2 dev eth-31-020.0.0.4/31 via
192.168.155.2 dev eth-31-020.0.0.6/31 via 192.168.155.2 dev
eth-31-020.0.0.8/31 via 192.168.155.2 dev eth-31-020.0.0.10/31 via
192.168.155.2 dev eth-31-020.0.0.12/31 via 192.168.155.2 dev
eth-31-020.0.0.14/31 via 192.168.155.2 dev eth-31-020.0.0.16/31 via
192.168.155.2 dev eth-31-020.0.0.18/31 via 192.168.155.2 dev
eth-31-020.0.0.20/31 via 192.168.155.2 dev eth-31-0
<...>20.0.0.242/31 via 192.168.155.2 dev eth-31-020.0.0.244/31 via
192.168.155.2 dev eth-31-020.0.0.246/31 via 192.168.155.2 dev
eth-31-020.0.0.248/31 via 192.168.155.2 dev eth-31-020.0.0.250/31 via
192.168.155.2 dev eth-31-020.0.0.252/31 via 192.168.155.2 dev
eth-31-020.0.0.254/31 via 192.168.155.2 dev eth-31-0172.17.0.0/16 dev
br-131bf7797fb8  proto kernel  scope link  src 172.17.0.1172.19.0.0/16
dev br-e7353579d7a2  proto kernel  scope link  src
172.19.0.1192.168.101.0/24 dev eth0  proto kernel  scope link  src
192.168.101.128192.168.155.0/24 dev eth-31-0  proto kernel  scope link
 src 192.168.155.3
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$

BUT never make it to the fib.

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh ip fib
 Table                   Destination           Adjacency
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.3/32  2: local eth-31-0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$

MOREOVER when i manually install a route:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
sudo ip ro add 30.0.0.240/31 via 192.168.155.2

The new route is not added to fib:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh ip fib
 Table                   Destination           Adjacency
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.3/32  2: local eth-31-0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$

Then I add a 2nd 30.x.x.x route:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
sudo ip ro add 30.0.0.242/31 via 192.168.155.2

The 2nd 30.x.x.x route appears in fib:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh ip fib
 Table                   Destination           Adjacency
     0                   20.0.0.0/31  4: rewrite eth-31-0 IP4:
02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0                 30.0.0.242/31  4: rewrite eth-31-0 IP4:
02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.2/32  3: rewrite eth-31-0 IP4:
02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0              192.168.155.3/32  2: local eth-31-0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$

And now, we see 192.168.155.2/32 for the first time.

The 1st 30.x.x.x route is indeed in the rib:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
ip ro | grep "30.0.0.240"30.0.0.240/31 via 192.168.155.2 dev eth-31-0

But not in the fib:

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh ip fib | grep "30.0.0.240"
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh ip fib | grep "30.0.0.242"
     0                 30.0.0.242/31  4: rewrite eth-31-0 IP4:
02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$

It feels like "the pump needs to be primed" somewhere, before the routes
are installed in the fib.

Maybe vnet requires NH 192.168.155.2/32 but linux does not.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/platinasystems/go/issues/12>, or mute the thread

**Comment by dlobete** [comment]
Hi Donn,

Some follow-up questions inline -

On Mon, Jan 23, 2017 at 1:58 PM, Donn Lee <notifications@github.com> wrote:

> I discovered that I can add rib routes quickly after 'goes start', and
> these routes will never make it to the fib. I think it is because linux
> installs the routes immediately, but fib is not ready yet (maybe because it
> requires next-hop /32 but linux does not?).
>
> I wrote a script that repros the fail:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ cat quick_add_routes.py
> #!/bin/bash
>
> set -x -e
>
> goes stop
> goes start
>
> sleep 6
>
> /sbin/ifdown eth-$1-0
> /sbin/ifup eth-$1-0
>
> /usr/bin/goes vnet set ha sp eth-$1-0 auto
> /usr/bin/goes vnet set ha sp eth-$1-0 100g
> /usr/bin/goes vnet set ha sp eth-$1-0 auto dis
> /usr/bin/goes vnet set ha sp eth-$1-0 auto ena
>
>
Is there a reason you use the vnet-level command versus redis ?

goes hset -q platina eth-x-0.speed auto

You can also do this in /etc/goes/start which runs your commands at goes
startup:

root@invader5:/home/dlobete/src/github.com/platinasystems/go# cat
/etc/goes/start
#!/usr/bin/goes
hset -q platina eth-0-0.media copper
hset -q platina eth-0-0.speed auto
hset -q platina eth-1-0.media copper
hset -q platina eth-1-0.speed auto
hset -q platina eth-2-0.media copper
hset -q platina eth-2-0.speed auto
hset -q platina eth-3-0.media copper
hset -q platina eth-3-0.speed auto
hset -q platina eth-27-0.speed 40g
hset -q platina eth-28-0.speed 40g
! ifup -a --allow vnet


>
> sleep 1
>
> #for i in {1..255};
> for i in `seq 0 2 255`;
>   do ip ro add 20.0.0.$i/31 via 192.168.155.2;
>   #do echo "20.0.0.$i/31 via 192.168.155.2";
> done
>
> The next-hop is 192.168.155.2 which is a neighboring router on this
> invader's eth-31-0.
>
> After 'goes start', eth-31-0 is in the following state:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ goes vnet sh fe1 po m | ta
> il
> eth-24-0  false       false        false
> eth-25-0  false       false        false
> eth-26-0  false       false        false
> eth-27-0  false       false        false
> eth-28-0  false       false        false
> eth-29-0  false       false        false
> eth-30-0  false       false        false
> eth-31-0  false        true        false
>
> To get the link in "true true true", I do the autoneg "dance" at the top
> of the script.
>
> /usr/bin/goes vnet set ha sp eth-$1-0 auto
> /usr/bin/goes vnet set ha sp eth-$1-0 100g
> /usr/bin/goes vnet set ha sp eth-$1-0 auto dis
> /usr/bin/goes vnet set ha sp eth-$1-0 auto ena
>
> Where $1 is "31" because I run the repro script like so:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ./quick_add_routes.py  31
>
> The script installs ~128 static routes. These routes are installed in rib:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ ip ro
> default via 192.168.101.2 dev eth010.2.0.0/16 dev flannel.1  proto kernel  scope link  src 10.2.65.010.2.65.0/24 dev docker0  proto kernel  scope link  src 10.2.65.120.0.0.0/31 via 192.168.155.2 dev eth-31-020.0.0.2/31 via 192.168.155.2 dev eth-31-020.0.0.4/31 via 192.168.155.2 dev eth-31-020.0.0.6/31 via 192.168.155.2 dev eth-31-020.0.0.8/31 via 192.168.155.2 dev eth-31-020.0.0.10/31 via 192.168.155.2 dev eth-31-020.0.0.12/31 via 192.168.155.2 dev eth-31-020.0.0.14/31 via 192.168.155.2 dev eth-31-020.0.0.16/31 via 192.168.155.2 dev eth-31-020.0.0.18/31 via 192.168.155.2 dev eth-31-020.0.0.20/31 via 192.168.155.2 dev eth-31-0
> <...>20.0.0.242/31 via 192.168.155.2 dev eth-31-020.0.0.244/31 via 192.168.155.2 dev eth-31-020.0.0.246/31 via 192.168.155.2 dev eth-31-020.0.0.248/31 via 192.168.155.2 dev eth-31-020.0.0.250/31 via 192.168.155.2 dev eth-31-020.0.0.252/31 via 192.168.155.2 dev eth-31-020.0.0.254/31 via 192.168.155.2 dev eth-31-0172.17.0.0/16 dev br-131bf7797fb8  proto kernel  scope link  src 172.17.0.1172.19.0.0/16 dev br-e7353579d7a2  proto kernel  scope link  src 172.19.0.1192.168.101.0/24 dev eth0  proto kernel  scope link  src 192.168.101.128192.168.155.0/24 dev eth-31-0  proto kernel  scope link  src 192.168.155.3
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> BUT never make it to the fib.
>

As we've discussed, I believe this is a known behavior of vnet - my
assumption is rtnetlink is not sending the neighbour/adjacency message
before the routes so vnet drops the route-adds. Will discuss this with
Eliot.

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
goes vnet sh ip fib
>  Table                   Destination           Adjacency
>      0              192.168.155.0/24  1: glean eth-31-0
>      0              192.168.155.3/32  2: local eth-31-0
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
>
> MOREOVER when i manually install a route:
>
> donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo ip ro add 30.0.0.240/31 via 192.168.155.2
>
> The new route is not added to fib:
>

Be good to understand the timeframes here -
How long from adjacency establishment (i.e. in ARP cache) does a route add
succeed ?  Could we add a loop with timestamp and print out vnet fib to see
when it does succeed?

I can try to replicate your rig and run your script  - need to setup a
neighboring invader.

Don.

**Comment by donnlee** [comment]
Fixed.
Re-tested and confirmed fixed.
Test output is stored on platina4:
~donn/invader_testing/issue12_before_fix.txt
~donn/invader_testing/issue12_after_fix.txt
