### ISSUE TITLE
Regression failure on setup-1 & setup-2

### ISSUE THREAD

**Issue by sandeep-dutta** [platinasystems/go#141]
As per the last regression run, following test cases failed to execute on setup-2  which caused the end result of regression as Failed.Also noticed the regression suit failed to execute further test cases.

- "frr_ospf_with_different_areas_2018112909:19:40: Failed"

**Comment by Ad9195** [comment]
The cause of failure of regression was due to a missing argument in a frr ospf traffic playbook.
Also during the execution of the very playbook vnet crashed.

15:26:54 ok: [invader45] => {
15:26:54     "goes.stdout": "GOES status\n======================\n  Mode            - XETH\n  PCI             - OK\n  Check daemons   - OK\n  Check Redis     - OK\n  Check vnet      - Not OK"
15:26:54 }
15:26:54 ok: [invader44] => {
15:26:54     "goes.stdout": "GOES status\n======================\n  Mode            - XETH\n  PCI             - OK\n  Check daemons   - OK\n  Check Redis     - OK\n  Check vnet      - Not OK"
15:26:54 }
15:26:54 ok: [invader43] => {
15:26:54     "goes.stdout": "GOES status\n======================\n  Mode            - XETH\n  PCI             - OK\n  Check daemons   - OK\n  Check Redis     - OK\n  Check vnet      - Not OK"
15:26:54 }
15:26:54 ok: [invader42] => {
15:26:54     "goes.stdout": "GOES status\n======================\n  Mode            - XETH\n  PCI             - OK\n  Check daemons   - OK\n  Check Redis     - OK\n  Check vnet      - Not OK"

**Comment by sandeep-dutta** [comment]
Regression triggered on setup-1

During 1st regression following test case have failed.
 "quagga_bgp_peering_loop_prevention_2018120607:58:35: Failed"
 "vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces_2018120612:05:26: Failed",
 "goes_boot_2018120612:47:54: Failed"

Noticed that during 1st regression run under “goes boot test case” when invader went for a reboot, goes services fail to come up on i-29.

root@invader29:/home/sandeep# goes status
GOES status
======================
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - Not OK
status: vnetd daemon not responding

**Comment by sandeep-dutta** [comment]
Regression executed on Setup-1

Noticed that Jenkins failed to send email for the regression run. However after looking into the Jenkins log only the following test case was found failed

-  "vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces_2018121911:59:11: Failed",

**Comment by RohanK-Calsoft** [comment]
As per the last regression triggered on setup-1 on 12/26/2018 [Regression no. 210 and 211] :-

During 1st regression following test case have failed.
"quagga_bgp_peering_ebgp_route_advertise_2018122608:35:09: Failed"
"quagga_bgp_convergence_2018122609:13:17: Failed",
"frr_bgp_convergence_2018122610:22:59: Failed"
"bird_bgp_peering_if_down_2018122611:33:34: Failed"
"dynamic_port_provision_10g_cr_fec_none_autoneg_off_lanes_1_count_4_2018122612:29:19: Failed"
"vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces_2018122613:06:15: Failed"

Noticed that majority (all except the last two of the list) of the above test-cases failed due to routes not being visible in the routing table (and leaf-leaf ping issues) even after adding a considerable amount of wait time. Those cases were verified manually by running the single playbook of that particular case isolately and they were passing.The inconsistency of these test-cases is observed only in the regression.

And the "vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces" case is failing since the vlan interface is fetching an ip from the physical ip subnet declared under dhcpd.conf file.



And During 2nd regression 
"quagga_bgp_peering_loop_prevention_2018122614:58:28: Failed" this test-case failed due to failure in finding the bgp loop prevention details in the log file /var/log/regression/bgp_loop_prevention.log".

Also, noticed that after the execution of the 'quagga' package, "Vnetd crash was observed on Invader30",
which is why the further regression failed.

root@invader30:/home/sandeep# goes status

GOES status
------------------------------
Mode - XETH
PCI - OK
Check daemons - OK
Check Redis - OK
Check vnet - Not OK
status: vnetd daemon not responding

So, we executed the following commands to reset it :-
rmmod platina-mk1
modprobe platina-mk1 provision=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
goes restart
ifdown -a --allow vnet
ifup -a --allow vnet

And then, the status was okay.

**Comment by RohanK-Calsoft** [comment]
As per the last regression triggered on setup-1 on 12/27/2018 [Regression no. 212 and 213] :-

For Both the 1st and the 2nd regression the failed test-cases are:-
"frr_bgp_convergence_2018122710:23:01: Failed"
"bird_bgp_peering_if_down_2018122711:33:11: Failed"
"vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces_2018122712:57:13: Failed"

Noticed that (except the last one of the list)  the above test-cases failed due to routes not being visible in the routing table (and leaf-leaf ping issues) even after adding a considerable amount of wait time. Those cases were verified manually by running the single playbook of that particular case isolately and they were "passing" .The inconsistency of these test-cases is observed only in the regression.

And the "vlan_configuration_dhcp_vlan_interfaces_and_physical_interfaces" case is failing since the vlan interface is fetching an ip from the physical ip subnet declared under dhcpd.conf file.

**Comment by sandeep-dutta** [comment]
Since we are maintaining a sheet with daily regression status. Closing this issue.
