### ISSUE TITLE
Counter constipation

### ISSUE THREAD

**Issue by dlobete** [platinasystems/go#2]
After many packets (60billion?) - redis counter update from vnet becomes slow and inconsistent.

**Comment by fszyang** [comment]
Fixed by commit 
Allow multiple real-time events to be processed (enqueue/drain)
7492da025e378fcb136eb9ce9dfd492d08aa656c

Following issues addressed by this commit and verified fixed:
- redis counter update slowing down after some time
- occasional redis i/o timeout error when doing hset
- occasional wide variation in counter update interval
