### ISSUE TITLE
deleting tuntap interface cause vnetd to panic

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#32]
Probably low priority since we're moving away from tuntap.

root@invader24:/home/stig# ip add sh eth-1-1
20411: eth-1-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4352 qdisc pfifo_fast state UP group default qlen 5000
    link/ether 6c:ec:5a:07:d1:a0 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.24/24 brd 10.0.1.255 scope global eth-1-1
       valid_lft forever preferred_lft forever
    inet6 fe80::6eec:5aff:fe07:d1a0/64 scope link 
       valid_lft forever preferred_lft forever

root@invader24:/home/stig# ip link del eth-1-1

Mar  1 21:08:02 invader24 goes.vnetd[32249]: panic: socket operation on non-socket
Mar  1 21:08:02 invader24 goes.vnetd[32249]: 
Mar  1 21:08:02 invader24 goes.vnetd[32249]: goroutine 18 [running]:
Mar  1 21:08:02 invader24 goes.vnetd[32249]: panic(0xe16e40, 0xc8211faae8)
Mar  1 21:08:02 invader24 goes.vnetd[32249]:         /usr/local/go/src/runtime/panic.go:464 +0x3e6
Mar  1 21:08:02 invader24 goes.vnetd[32249]: github.com/platinasystems/go/vnet/unix.(*Interface).ErrorReady(0xc82035f400, 0x7f270e4a4050, 0xc8211faae8)
Mar  1 21:08:02 invader24 goes.vnetd[32249]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/node.go:366 +0xc8
Mar  1 21:08:02 invader24 goes.vnetd[32249]: github.com/platinasystems/go/elib/iomux.(*Mux).do(0x1924500, 0xc82049b300)
Mar  1 21:08:02 invader24 goes.vnetd[32249]:         /home/stig/go/src/github.com/platinasystems/go/elib/iomux/epoll.go:153 +0x329
Mar  1 21:08:02 invader24 goes.vnetd[32249]: github.com/platinasystems/go/elib/iomux.(*Mux).EventPoll(0x1924500)
Mar  1 21:08:02 invader24 goes.vnetd[32249]:         /home/stig/go/src/github.com/platinasystems/go/elib/iomux/epoll.go:166 +0x24b
Mar  1 21:08:02 invader24 goes.vnetd[32249]: github.com/platinasystems/go/elib/loop.(*eventLoop).eventPoller(0xc8200d4e70, 0x7f270e3e4000, 0x1924500)
Mar  1 21:08:02 invader24 goes.vnetd[32249]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x27
Mar  1 21:08:02 invader24 goes.vnetd[32249]: created by github.com/platinasystems/go/elib/loop.(*eventLoop).startPoller
Mar  1 21:08:02 invader24 goes.vnetd[32249]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:161 +0x49
Mar  1 21:08:04 invader24 goes.vnetd[32249]: exit status 2

**Comment by stigt** [comment]
This no longer causes a panic, so closing and adding test case.

```
stig@invader1:~$ ip add sh eth-21-0
1711: eth-21-0: <BROADCAST,UP,LOWER_UP> mtu 9216 qdisc pfifo_fast state UP group default qlen 5000
    link/ether 02:46:8a:00:02:ee brd ff:ff:ff:ff:ff:ff
    inet 10.50.0.1/24 brd 10.50.0.255 scope global eth-21-0
       valid_lft forever preferred_lft forever
    inet6 fe80::46:8aff:fe00:2ee/64 scope link 
       valid_lft forever preferred_lft forever
stig@invader1:~$ 
stig@invader1:~$ ping 10.50.0.11
PING 10.50.0.11 (10.50.0.11) 56(84) bytes of data.
64 bytes from 10.50.0.11: icmp_seq=1 ttl=64 time=0.916 ms
^C
--- 10.50.0.11 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.916/0.916/0.916/0.000 ms

stig@invader1:~$ sudo ip link del eth-21-0
stig@invader1:~$ sudo goes status
GOES status
======================
  Mode            - TUNTAP
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

stig@invader1:~$ ip link show eth-21-0
Device "eth-21-0" does not exist.

```

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build (Now moved out of TUNTAP,tested this on XETH) :-

root@invader44:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader44:/home/rohan# goes version
v1.1.1

1) Checked whether the interface was working fine.
root@invader44:/# ip add sh xeth5
327: xeth5@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 50:18:4c:00:06:28 brd ff:ff:ff:ff:ff:ff
    inet 10.0.5.30/24 brd 10.0.5.255 scope global xeth5
       valid_lft forever preferred_lft forever
    inet6 fe80::5218:4cff:fe00:628/64 scope link
       valid_lft forever preferred_lft forever

root@invader44:/# ping 10.0.5.30
PING 10.0.5.30 (10.0.5.30) 56(84) bytes of data.
64 bytes from 10.0.5.30: icmp_seq=1 ttl=64 time=7.28 ms
64 bytes from 10.0.5.30: icmp_seq=2 ttl=64 time=1.18 ms
64 bytes from 10.0.5.30: icmp_seq=3 ttl=64 time=1.12 ms
^C
--- 10.0.5.30 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 1.123/3.195/7.280/2.888 ms

2) Tried deleting the xeth interface:-
root@invader44:/# sudo ip link del xeth5 
**RTNETLINK answers: Operation not supported**

3) Checked the goes status and the link:-
root@invader44:/# goes status
GOES status
------------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

root@invader44:/# ip link show xeth5
327: xeth5@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:06:28 brd ff:ff:ff:ff:ff:ff

**Result**:-The issue is not reproducing on 'xeth'.
